OPENEUROPA-2622: Add 'Location' field type and add 'Project locations' field to Project content type.
openeuropa/oe_content pull request #255
Opened 2020-08-27 08:57 UTC by yenyasinn

## OPENEUROPA-2622

### Description

"Project locations" (machine name 'oe_project_locations') field has been added to Project node.

2020-08-28 09:47 UTC, nagyad approved these changes

2020-08-28 11:33 UTC, nagyad requested changes
Missing address module from dependencies.

2020-08-31 10:21 UTC, ademarco approved these changes

2020-08-31 10:23 UTC, nagyad approved these changes

2020-08-31 10:24 UTC, merged