EWPP-119: Redirect outbound processor.
openeuropa/oe_content pull request #258
Opened 2020-09-01 07:34 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-09-08 08:23 UTC, brummbar requested changes

2020-09-08 08:23 UTC, brummbar commented on modules/oe_content_redirect_link_field/tests/src/Kernel/PathProcessorRedirectLinkTest.php
> +}
Cache propagation tests are missing.

2020-09-08 08:36 UTC, brummbar commented on modules/oe_content_redirect_link_field/src/PathProcessor/PathProcessorRedirectLink.php
> +    }
Old comment

2020-09-08 08:48 UTC, upchuk commented on modules/oe_content_redirect_link_field/tests/src/Kernel/PathProcessorRedirectLinkTest.php
> +    $this->assertEquals($url, $url);
lol. Why not? :)

2020-09-08 08:49 UTC, upchuk commented on modules/oe_content_redirect_link_field/tests/src/Kernel/PathProcessorRedirectLinkTest.php
> +    $this->assertEquals($url, $url);
:))

2020-09-08 09:00 UTC, sergepavle commented on modules/oe_content_redirect_link_field/tests/src/Kernel/PathProcessorRedirectLinkTest.php
> +    $this->assertEquals($url, $url);
oh no... it wasn't with evil intention or try to cheat.. just happened... sorry

2020-09-09 09:40 UTC, brummbar approved these changes

2020-09-09 11:05 UTC, upchuk approved these changes

2020-09-09 11:05 UTC, merged