EWPP-272: News type field with Skos concept subset.
openeuropa/oe_content pull request #282
Opened 2020-09-16 14:05 UTC by upchuk

* Added the News type field
* Created the Concept subset plugin to only be able to select certain resource types for the News type field.

2020-09-21 13:26 UTC, ademarco requested changes

2020-09-21 13:26 UTC, ademarco commented on modules/oe_content_news/src/Plugin/ConceptSubset/ResourceTypesNews.php
> + *   id = "resource_types_news",
```suggestion
 *   id = "oe_content_news_resource_types_news",
```

2020-09-21 13:26 UTC, ademarco commented on modules/oe_content_news/config/install/field.field.node.oe_news.oe_news_types.yml
> +    concept_subset: resource_types_news
```suggestion
    concept_subset: oe_content_news_resource_types_news
```

2020-09-21 13:26 UTC, ademarco commented on modules/oe_content_news/config/post_updates/00002/field.field.node.oe_news.oe_news_types.yml
> +    concept_subset: resource_types_news
```suggestion
    concept_subset: oe_content_news_resource_types_news
```

2020-09-21 13:26 UTC, ademarco commented on modules/oe_content_news/src/Plugin/ConceptSubset/ResourceTypesNews.php
> +    $query->condition('resource_types_news', 'http://publications.europa.eu/resource/authority/use-context/COM_NEWS');
```suggestion
    $query->condition('oe_content_news_resource_types_news', 'http://publications.europa.eu/resource/authority/use-context/COM_NEWS');
```

2020-09-21 13:26 UTC, ademarco commented on modules/oe_content_news/src/Plugin/ConceptSubset/ResourceTypesNews.php
> +    $mapping['resource_types_news'] = [
```suggestion
    $mapping['oe_content_news_resource_types_news'] = [
```

2020-09-21 13:26 UTC, ademarco commented on modules/oe_content_news/src/Plugin/ConceptSubset/ResourceTypesNews.php
> +    $fields['resource_types_news'] = BaseFieldDefinition::create('string')
```suggestion
    $fields['oe_content_news_resource_types_news'] = BaseFieldDefinition::create('string')
```

2020-09-22 06:08 UTC, ademarco requested changes
Set default value for type field to "News article"

2020-09-22 12:59 UTC, ademarco requested changes

2020-09-22 12:59 UTC, ademarco commented on modules/oe_content_news/oe_content_news.post_update.php
> +}
Split this into 2 update path:
1. Create new field.
2. Update form display.

so that if one fail on prod we know which one.

2020-09-22 14:09 UTC, imanoleguskiza commented on modules/oe_content_news/src/Plugin/ConceptSubset/ResourceTypesNews.php
> +class ResourceTypesNews extends ConceptSubsetPluginBase implements PredicateMapperInterface {
We need tests for this subset right?

2020-09-22 15:27 UTC, imanoleguskiza approved these changes

2020-09-22 16:00 UTC, ademarco approved these changes

2020-09-22 16:00 UTC, merged