EWPP-204: Organisation type fields.
openeuropa/oe_content pull request #290
Opened 2020-09-23 11:57 UTC by upchuk

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-09-25 13:53 UTC, nagyad commented
Integration part will be done in EWPP-280 organisation integration ticket.

2020-09-28 06:46 UTC, upchuk commented on tests/features/organisation.feature
> +    And I fill in "Non-EU organisation type" with "foundation"
Why do you fill this in?

2020-09-28 06:46 UTC, upchuk commented on modules/oe_content_organisation/tests/src/Kernel/OrganisationFieldTest.php
> +   * Modules to enable.
inheritdoc

2020-09-28 06:46 UTC, upchuk commented on modules/oe_content_organisation/oe_content_organisation.module
> +    $form_state->setErrorByName('oe_organisation_eu_org', t('Please select an EU organisation.'));
This is not tested in your Behat scenario. There should be a step that removes the browser-side "required" validation so you can submit the form and test this as well.

2020-09-28 06:46 UTC, upchuk commented on modules/oe_content_organisation/oe_content_organisation.module
> +    $form_state->setErrorByName('oe_organisation_non_eu_org_type', t('Please select an non-EU organisation type.'));
Same as above.

2020-09-28 08:26 UTC, 22Alexandra requested changes

2020-09-28 08:26 UTC, 22Alexandra commented on modules/oe_content_organisation/oe_content_organisation.module
> +      ['select[name="oe_organisation_org_type"]' => ['value' => 'non_eu']]
Outer square brackets not needed. The same for the other 3 states arrays.

2020-09-28 08:26 UTC, 22Alexandra commented on modules/oe_content_organisation/oe_content_organisation.module
> +    $form_state->setErrorByName('oe_organisation_non_eu_org_type', t('Please select an non-EU organisation type.'));
```suggestion
    $form_state->setErrorByName('oe_organisation_non_eu_org_type', t('Please select a non-EU organisation type.'));
```

2020-09-28 08:26 UTC, 22Alexandra commented on modules/oe_content_organisation/tests/src/Kernel/OrganisationFieldTest.php
> +    'typed_link',
Not needed.

2020-09-28 08:26 UTC, 22Alexandra commented on modules/oe_content_organisation/tests/src/Kernel/OrganisationFieldTest.php
> +    'link',
Not needed.

2020-09-28 08:26 UTC, 22Alexandra commented on modules/oe_content_organisation/tests/src/Kernel/OrganisationFieldTest.php
> +    $this->installSchema('node', 'node_access');
Not needed.

2020-09-28 08:26 UTC, 22Alexandra commented on modules/oe_content_organisation/tests/src/Kernel/OrganisationFieldTest.php
> +    $this->installSchema('user', 'users_data');
Not needed.

2020-09-28 08:26 UTC, 22Alexandra commented on tests/features/organisation.feature
> +  Scenario: Organisation type fields is required based on Please select an EU organisation. selection.
```suggestion
  Scenario: Organisation type fields are required based on selected type.
```

2020-09-28 08:26 UTC, 22Alexandra commented on tests/features/organisation.feature
> +    And I fill in "Teaser" with "Organisation teaser text"
These extra steps are not necessary.

2020-09-28 08:51 UTC, nagyad commented on tests/features/organisation.feature
> +  Scenario: Organisation type fields is required based on Please select an EU organisation. selection.
Scenario is removed.

2020-09-28 08:51 UTC, nagyad commented on tests/features/organisation.feature
> +    And I fill in "Teaser" with "Organisation teaser text"
Scenario is removed.

2020-09-28 09:07 UTC, 22Alexandra commented on tests/Behat/MinkContext.php
> +  /**
What is this needed for?

2020-09-28 09:08 UTC, 22Alexandra commented on tests/Behat/MinkContext.php
> +  }
What is this needed for?

2020-09-28 09:12 UTC, 22Alexandra submitted a review, later dismissed

2020-09-28 12:07 UTC, ademarco approved these changes

2020-09-28 12:27 UTC, 22Alexandra approved these changes

2020-09-28 12:36 UTC, merged