EWPP-323: Add av portal to logo sources.
openeuropa/oe_content pull request #299
Opened 2020-09-29 09:32 UTC by drishu

## EWPP-323

### Description

Add av portal to logo sources.

### Change log

- Added: test for av portal value in organisation test
- Changed: logo field settings

2020-09-29 13:15 UTC, nagyad approved these changes

2020-09-29 14:14 UTC, nagyad requested changes

2020-09-29 14:14 UTC, nagyad commented on modules/oe_content_organisation/README.md
> +    "openeuropa/oe_media": "dev-master"
dev-master?? this it not good.

2020-09-29 14:18 UTC, nagyad commented on modules/oe_content_organisation/README.md
> +    "openeuropa/oe_media": "dev-master"
This should be removed from here.

2020-09-29 14:53 UTC, nagyad approved these changes

2020-09-29 14:55 UTC, ademarco approved these changes

2020-09-29 16:39 UTC, ademarco approved these changes

2020-09-30 06:33 UTC, nagyad approved these changes

2020-09-30 06:40 UTC, nagyad approved these changes

2020-09-30 06:40 UTC, merged