EWPP-516: Update docker images.
openeuropa/oe_content pull request #343
Opened 2020-11-13 09:46 UTC by 22Alexandra

2020-11-17 17:10 UTC, sergepavle submitted a review, later dismissed

2020-11-18 14:55 UTC, nagyad requested changes

2020-11-18 14:55 UTC, nagyad commented on docker-compose.yml
> +    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-debug-3.141.59
Why not like in media_avportal?
![image](https://user-images.githubusercontent.com/22004498/99546187-780f7e00-29b6-11eb-8265-c2fb45a81e35.png)

2020-11-18 15:02 UTC, nagyad approved these changes

2020-11-25 14:54 UTC, sergepavle approved these changes

2020-11-25 16:14 UTC, nagyad approved these changes

2020-11-27 12:59 UTC, sergepavle approved these changes

2020-11-27 13:32 UTC, nagyad approved these changes

2020-11-27 13:38 UTC, merged