EWPP-436: Fix oe_call_proposals_journal instance config.
openeuropa/oe_content pull request #344
Opened 2020-11-13 16:45 UTC by drishu

## EWPP-436

### Description

Update the oe_call_proposals_journal instance configuration to not be translatable as convened.

### Change log

- Changed: oe_call_proposals_journal config

2020-11-13 16:55 UTC, nagyad submitted a review, later dismissed

2020-11-16 10:56 UTC, nagyad approved these changes

2020-11-16 11:08 UTC, nagyad requested changes

2020-11-16 11:08 UTC, nagyad commented on tests/Behat/Content/Node/CallForProposalsContentContext.php
> +          $fields = $this->getReferenceRevisionField($mapping[$key], 'oe_contact', $value);
Contacts is missing from the $mapping.

2020-11-16 12:44 UTC, nagyad approved these changes

2020-11-16 13:32 UTC, imanoleguskiza approved these changes

2020-11-16 13:34 UTC, merged