EWPP-564: Installing the newly created SKOS field definitions.
openeuropa/oe_content pull request #350
Opened 2020-11-26 10:54 UTC by upchuk

See https://github.com/openeuropa/rdf_skos/pull/59

2020-11-27 10:53 UTC, brummbar requested changes

2020-11-27 10:53 UTC, brummbar commented on modules/oe_content_news/oe_content_news.install
> +  /** @var \Drupal\rdf_skos\SkosEntityDefinitionUpdateManager $update_manager */
We need to limit at least the definition installation to the fields defined by this very module.

2020-12-01 16:38 UTC, brummbar approved these changes

2020-12-02 15:41 UTC, hernani approved these changes

2020-12-02 16:15 UTC, merged