FPFISSUPP-10258: Update xdebug3.
openeuropa/oe_content pull request #368
Opened 2020-12-14 16:55 UTC by voidtek

## FPFISSUPP-10258

### Description

Update docker compose for xdebug3

2020-12-15 09:11 UTC, imanoleguskiza requested changes

2020-12-15 09:11 UTC, imanoleguskiza commented on docker-compose.yml
> +      XDEBUG_MODE: "develop,debug,coverage,gcstats,profile,trace"
We need to enable only debug.

2020-12-15 09:42 UTC, brummbar requested changes

2020-12-15 09:42 UTC, brummbar commented on docker-compose.yml
> +    image: registry.fpfis.eu/fpfis/httpd-php:7.3-dev
We didn't update the images as the ones behind registry.fpfis.eu/fpfis/ require a Gitlab account and this is a major problem for the opensource side of OpenEuropa. Everybody should be able to setup the component locally. So no images in docker-compose.yml should be touched.

2021-11-09 11:07 UTC, imanoleguskiza commented
Xdebug 3 configuration was merged in a separate pr

2021-11-09 11:07 UTC, closed without merging