EWPP-686: Characters in Timeline Label field causing "unexpected error".
openeuropa/oe_content pull request #381
Opened 2021-01-25 18:05 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-01-26 09:31 UTC, georgebaev approved these changes

2021-01-26 13:50 UTC, drishu requested changes
other then that this works great

2021-01-27 08:13 UTC, drishu submitted a review, later dismissed

2021-01-28 14:08 UTC, nagyad approved these changes

2021-02-25 11:40 UTC, ademarco approved these changes

2021-02-25 12:09 UTC, drishu requested changes

2021-02-25 12:09 UTC, drishu commented on modules/oe_content_timeline_field/tests/Kernel/TimelineFieldTest.php
> +          'format' => 'format_☺',
If we don't change the type for `format` then this will fail, so either we change it or we amend this, same below

2021-02-25 12:45 UTC, ademarco approved these changes

2021-02-25 12:58 UTC, drishu submitted a review, later dismissed

2021-02-25 13:12 UTC, ademarco requested changes
Preventing this to be merged until acceptance tests are done.

2021-03-02 11:05 UTC, ademarco approved these changes

2021-03-02 11:38 UTC, georgebaev approved these changes

2021-03-02 11:55 UTC, drishu approved these changes

2021-03-02 12:09 UTC, ademarco approved these changes

2021-03-02 12:50 UTC, merged