EWPP-1043: Create a Link field on the General and Press Contact bundle
openeuropa/oe_content pull request #418
Opened 2021-04-21 15:10 UTC by yenyasinn

2021-04-22 07:23 UTC, 22Alexandra submitted a review, later dismissed

2021-04-22 08:32 UTC, upchuk requested changes

2021-04-22 08:32 UTC, upchuk commented on modules/oe_content_entity/modules/oe_content_entity_contact/config/install/field.field.oe_contact.oe_press.oe_link.yml
> +translatable: true
Why true here and not thee press one? This should be false.

2021-04-22 08:32 UTC, upchuk commented on modules/oe_content_entity/modules/oe_content_entity_contact/config/post_updates/00008_create_link_field/field.field.oe_contact.oe_press.oe_link.yml
> +translatable: true
Same here

2021-04-22 08:36 UTC, upchuk submitted a review, later dismissed

2021-04-22 08:37 UTC, 22Alexandra approved these changes, later dismissed

2021-04-26 05:43 UTC, upchuk approved these changes

2021-04-26 06:13 UTC, 22Alexandra approved these changes

2021-04-26 06:13 UTC, merged