EWPP-1366: Add Persons entity reference field storage.
openeuropa/oe_content pull request #451
Opened 2021-08-05 13:26 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-08-10 13:58 UTC, 22Alexandra requested changes
This module should be a submodule of `oe_content_person`.

2021-08-10 13:58 UTC, 22Alexandra commented on modules/oe_content_person_reference/oe_content_person_reference.info.yml
> +description: Allows to reference persons by, for example, providing an entity reference field.
```suggestion
description: Contains the persons entity reference storage field.
```

2021-08-10 13:58 UTC, 22Alexandra commented on modules/oe_content_person_reference/oe_content_person_reference.info.yml
> +  - drupal:field
We need to add a dependency on oe_content_person submodule.

2021-08-11 08:19 UTC, 22Alexandra approved these changes, later dismissed

2021-08-11 09:20 UTC, nagyad requested changes

2021-08-11 09:20 UTC, nagyad commented on modules/oe_content_person/modules/oe_content_person_reference/README.md
> +# OpenEuropa Persons Field
The module name should be OpenEuropa Person Reference.

2021-08-11 09:20 UTC, nagyad commented on modules/oe_content_person/modules/oe_content_person_reference/oe_content_person_reference.info.yml
> +name: OpenEuropa Content Persons Field
The module name should be OpenEuropa Person Reference.

2021-08-11 13:33 UTC, nagyad approved these changes

2021-08-11 14:21 UTC, 22Alexandra approved these changes

2021-08-12 13:57 UTC, merged