EWPP-1488: Adds access control handler for corporate entity types and sub entity types.
openeuropa/oe_content pull request #467
Opened 2021-09-13 14:52 UTC by 22Alexandra

2021-09-14 14:50 UTC, nagyad requested changes
The description of the ticket stated to create a single access control handler that will handle both cases. Let's adapt the code accordingly.

2021-09-15 13:47 UTC, nagyad requested changes

2021-09-15 13:47 UTC, nagyad commented on modules/oe_content_entity/src/CorporateEntityTypeAccessControlHandler.php
> +        return AccessResult::allowedIf($account->hasPermission("view published $corporate_entity_id") || $account->hasPermission('access content'));
Try to adapt this to void calling ($account->hasPermission("view published $corporate_entity_id") when $corporate_entity_id is null.

2021-09-15 13:52 UTC, nagyad submitted a review, later dismissed

2021-09-16 12:13 UTC, sergepavle commented on modules/oe_content_sub_entity/tests/src/Kernel/SubEntityAccessControlHandlerTest.php
> +      ],
As I understand these test cases are applied for access `view label` operation of the **sub-entity**, but according to changes it has to be applied to **sub-entity type** (bundle).

2021-09-16 12:13 UTC, sergepavle commented on modules/oe_content_entity/tests/src/Kernel/CorporateEntityAccessControlHandlerTest.php
> +      ],
As I understand these test cases are applied for access `view label` operation of the **corporate entity**, but according to changes it has to be applied to **corporate type entity** (bundle).

2021-09-17 07:54 UTC, sergepavle commented on modules/oe_content_sub_entity/tests/src/Kernel/SubEntityAccessControlHandlerTest.php
> +    }
```suggestion
    $scenarios = $this->bundleAccessTestScenarios();
    $type_storage = $this->container->get('entity_type.manager')->getStorage('oe_sub_entity_type_test');
    $subentity_bundle = $type_storage->create([
      'id' => 'test_bundle',
      'label' => 'Test bundle',
    ]);
    $subentity_bundle->save();
    foreach ($scenarios as $scenario => $test_data) {
      $user = $this->drupalCreateUser($test_data['permissions']);
      $this->assertAccessResult(
        $test_data['expected_result'],
        $this->bundleAccessControlHandler->access($subentity_bundle, $test_data['operation'], $user, TRUE),
        sprintf('Failed asserting access for "%s" scenario.', $scenario)
      );
    }
```

2021-09-17 10:48 UTC, sergepavle approved these changes, later dismissed

2021-09-17 14:44 UTC, nagyad requested changes

2021-09-17 14:44 UTC, nagyad commented on modules/oe_content_entity/src/CorporateEntityTypeAccessControlHandler.php
> +        }
We don't have to wrap this into an else.

2021-09-17 14:44 UTC, nagyad commented on modules/oe_content_entity/tests/src/Kernel/CorporateEntityAccessControlHandlerTest.php
> +  protected $entity;
I don't see why we need this global variable at all. You create an entity during setup, that is being used only in one test case so far, for other test cases it's not being used but still it is being created.

2021-09-20 09:37 UTC, nagyad approved these changes, later dismissed

2021-09-20 11:14 UTC, sergepavle approved these changes, later dismissed

2021-09-23 08:19 UTC, sergepavle approved these changes

2021-09-23 08:49 UTC, upchuk approved these changes
Approving on behalf of Adam.

2021-09-23 08:49 UTC, merged