[EWPP-1539] EWPP-1669: Add event collection functionality.
openeuropa/oe_content pull request #487
Opened 2021-11-08 11:50 UTC by yenyasinn

2021-11-09 09:17 UTC, 22Alexandra requested changes
The build has a test failing on both highest and lowest so it can't be random. The epic branch might need to be updated.

2021-11-09 14:57 UTC, yenyasinn commented
> The build has a test failing on both highest and lowest so it can't be random. The epic branch might need to be updated.

PR has been restarted and it's green now.

2021-11-11 15:28 UTC, 22Alexandra approved these changes

2021-11-17 11:09 UTC, nagyad approved these changes

2021-11-17 13:39 UTC, merged