[EWPP-1539] EWPP-1755: Add optional module which bring Event speaker entity type.
openeuropa/oe_content pull request #492
Opened 2021-11-19 16:12 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-11-23 12:33 UTC, nagyad requested changes

2021-11-23 12:33 UTC, nagyad commented on modules/oe_content_event/modules/oe_content_event_person_reference/src/Entity/EventSpeakerInterface.php
> + * Represents a Event speaker entity.
Represents an...

2021-11-23 12:33 UTC, nagyad commented on modules/oe_content_event/modules/oe_content_event_person_reference/tests/src/Kernel/EventSpeakerEntityTest.php
> +   * Tests label of extra author entities.
Tests label of event speaker entities.

2021-11-23 13:28 UTC, nagyad approved these changes, later dismissed

2021-11-24 12:27 UTC, 22Alexandra approved these changes

2021-11-24 14:08 UTC, nagyad approved these changes

2021-11-25 11:58 UTC, merged