EWPP-1802: Improve live stream display.
openeuropa/oe_content pull request #498
Opened 2021-12-07 16:28 UTC by yenyasinn

2021-12-07 17:52 UTC, yenyasinn commented on modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_online_link.yml
> +  title: 2
From the spec
<img width="1107" alt="Screenshot 2021-12-07 at 20 51 15" src="https://user-images.githubusercontent.com/1183951/145080829-bcb54cec-ab67-47fd-95b7-a99960a57e8d.png">

2021-12-09 19:05 UTC, sergepavle approved these changes, later dismissed

2021-12-09 19:05 UTC, sergepavle commented on modules/oe_content_event/src/EventNodeWrapper.php
> +    return $this->hasOnlineDates() && $datetime >= $this->getOnlineEndDate()->getPhpDateTime();
```suggestion
    return $datetime >= $this->getOnlineEndDate()->getPhpDateTime();
```

2021-12-20 14:05 UTC, 22Alexandra commented on modules/oe_content_event/src/EventNodeWrapper.php
> +    return $this->hasOnlineDates() && $datetime >= $this->getOnlineEndDate()->getPhpDateTime();
I'd keep the check.

2021-12-20 14:51 UTC, 22Alexandra approved these changes, later dismissed

2022-01-03 15:10 UTC, nagyad approved these changes, later dismissed

2022-01-05 12:17 UTC, sergepavle submitted a review, later dismissed

2022-01-05 12:41 UTC, nagyad approved these changes, later dismissed

2022-01-07 08:13 UTC, imanoleguskiza requested changes

2022-01-07 08:13 UTC, imanoleguskiza commented on modules/oe_content_event/src/EventNodeWrapper.php
> +    if (!$this->hasOnlineDates()) {
This check is not needed, we already check in the main return

2022-01-07 08:13 UTC, imanoleguskiza commented on modules/oe_content_event/src/EventNodeWrapper.php
> +      return TRUE;
This is a bit misleadin, if there are no online dates its neither over nor it has not started. Lets follow the same logic as in isRegistrationPeriodOver.

2022-01-07 12:36 UTC, imanoleguskiza approved these changes

2022-01-07 12:36 UTC, imanoleguskiza approved these changes

2022-01-07 12:39 UTC, nagyad approved these changes

2022-01-07 12:39 UTC, merged