EWPP-1915: Update to PHP8
openeuropa/oe_content pull request #512
Opened 2022-02-08 12:57 UTC by yenyasinn

2022-02-08 13:34 UTC, 22Alexandra requested changes
Since there are no failures within this PR, please check https://drone.fpfis.eu/openeuropa/oe_theme/6838/82 because the entity form display config files come from oe_content and they need to be fixed in here.

2022-02-08 15:19 UTC, 22Alexandra commented on composer.json
>          "easyrdf/easyrdf": "1.0.0 as 0.9.2",
This dependency is part of rdf_skos.

2022-02-10 10:51 UTC, hernani commented on composer.json
>          "easyrdf/easyrdf": "1.0.0 as 0.9.2",
Can be removed.

2022-02-10 10:52 UTC, 22Alexandra commented
> Since there are no failures within this PR, please check https://drone.fpfis.eu/openeuropa/oe_theme/6838/82 because the entity form display config files come from oe_content and they need to be fixed in here.

Nmv, I was wrong.

2022-02-10 16:16 UTC, hernani approved these changes

2022-02-10 16:19 UTC, 22Alexandra approved these changes

2022-02-10 16:19 UTC, merged