EWPP-1777: Enable 'Include past revisions' option in composite fields.
openeuropa/oe_content pull request #534
Opened 2022-05-02 12:50 UTC by yenyasinn

2022-05-12 13:09 UTC, nagyad submitted a review, later dismissed

2022-05-13 08:32 UTC, 22Alexandra requested changes

2022-05-13 08:32 UTC, 22Alexandra commented on modules/oe_content_event/oe_content_event.post_update.php
> +    'oe_event_speaker.oe_default.oe_person' => FALSE,
This config belongs to the submodule providing the EventSpeaker subentity, so I think it should be updated in a post_update of the submodule. The submodule is not a dependency of the main module so the config might not event exist in some cases.

2022-05-13 08:32 UTC, 22Alexandra commented on modules/oe_content_organisation/oe_content_organisation.post_update.php
> +    'oe_contact.oe_organisation_reference.oe_node_reference' => FALSE,
The same remark as for the EventSpeaker field config.

2022-05-13 08:32 UTC, 22Alexandra commented on modules/oe_content_organisation/modules/oe_content_organisation_person_reference/config/install/field.field.node.oe_organisation.oe_organisation_persons.yml
> +    composite_revisions: false
This field config should be updated in a post_update too.

2022-05-13 08:32 UTC, 22Alexandra commented on modules/oe_content_publication/oe_content_publication.post_update.php
> +
This is updated in the loop.
```suggestion
```

2022-05-13 16:21 UTC, 22Alexandra approved these changes

2022-05-16 08:31 UTC, nagyad approved these changes

2022-05-16 11:40 UTC, merged