OEL-1550: Make oe_content_publication optional in oe_content_sub_entity_document_reference.
openeuropa/oe_content pull request #535
Opened 2022-05-10 13:02 UTC by escuriola

## OPENEUROPA-1550

### Description

Make oe_content_publication optional in oe_content_sub_entity_document_reference.

### Change log

- Added:
- Changed: oe_publication reference files has been moved from install to optional, remove from info.yml and fixed tests.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-06-21 17:04 UTC, drishu reviewed
I changed the PR target since its part of an epic

2022-06-23 14:38 UTC, drishu requested changes

2022-06-23 14:38 UTC, drishu commented on modules/oe_content_publication/modules/oe_content_publication_document_reference/oe_content_publication_document_reference.info.yml
> +config_devel:
this bit should be removed

2022-06-23 14:42 UTC, drishu submitted a review, later dismissed

2022-06-23 15:16 UTC, drishu approved these changes

2022-06-23 15:17 UTC, brummbar commented on modules/oe_content_publication/modules/oe_content_publication_document_reference/oe_content_publication_document_reference.info.yml
> +config_devel:
Fixed, thanks!

2022-06-23 16:20 UTC, brummbar approved these changes
Approving after @escuriola review.

2022-06-23 16:20 UTC, merged