EWPP-2746: Migrate the person data to the new sub entities.
openeuropa/oe_content pull request #555
Opened 2022-11-21 16:39 UTC by yenyasinn

2022-11-28 15:33 UTC, nagyad requested changes

2022-11-28 15:33 UTC, nagyad commented on modules/oe_content_sub_entity/modules/oe_content_sub_entity_person/src/PersonNodeUpdater.php
> +      ->execute();
We are using entity query here, all entity queries are executed with access check unless it is explicitly specified not to. For what we are doing here, we don't want access checks to be performed. Please use accessCheck(FALSE) in the query.

2022-11-28 15:33 UTC, nagyad commented on modules/oe_content_sub_entity/modules/oe_content_sub_entity_person/tests/src/Kernel/PersonNodeUpdaterTest.php
> +  public static $modules = [
Shall we introduce a kernel test base?

2022-11-28 15:33 UTC, nagyad commented on modules/oe_content_sub_entity/modules/oe_content_sub_entity_person/README.md
> +    // Get all the nodes which have author.
... which have person.

2022-11-29 18:43 UTC, sergepavle approved these changes, later dismissed

2022-12-01 09:01 UTC, sergepavle approved these changes

2022-12-01 09:12 UTC, nagyad approved these changes

2022-12-01 09:13 UTC, merged