EWPP-2814: Adapt the timeline field processor.
openeuropa/oe_content pull request #580
Opened 2023-03-24 10:45 UTC by 22Alexandra

2023-04-11 15:01 UTC, upchuk requested changes

2023-04-11 15:01 UTC, upchuk commented on modules/oe_content_timeline_field/src/TimelineFieldProcessor.php
> +use Drupal\oe_translation\TranslationSourceFieldProcessor\DefaultFieldProcessor;
You are using the same class here regardless of whether it exists or not..

2023-04-19 07:16 UTC, upchuk approved these changes

2023-04-19 07:19 UTC, brummbar approved these changes

2023-04-19 07:19 UTC, merged