EWPP-3305: Fix date translations and remove duplicates.
openeuropa/oe_content pull request #588
Opened 2023-06-08 10:52 UTC by nagyad

2023-06-13 11:05 UTC, 22Alexandra requested changes

2023-06-13 11:05 UTC, 22Alexandra commented on translations/oe_content-el.po
> -
All long month names need to be updated for EL.

2023-06-13 11:05 UTC, 22Alexandra commented on translations/oe_content-fi.po
> -
All long month names need to be updated for FI.

2023-06-13 11:05 UTC, 22Alexandra commented on translations/oe_content-hr.po
> -
Please update the long month names.

2023-06-13 11:05 UTC, 22Alexandra commented on translations/oe_content-da.po
> +msgstr "jan."
Why this dot? I might misunderstand the excel sheet but the dot is after the day, not after the month:
<img width="568" alt="DA - short month name" src="https://github.com/openeuropa/oe_content/assets/22908988/fd4ea6f2-9f9a-4558-8f25-4e054f7f0ef5">

I think we might need to remove the dot from every month name.

2023-06-13 11:05 UTC, 22Alexandra commented on translations/oe_content-ro.po
> -
For RO I don't see any dot after the short month name, I think we need to remove it (seems outdated).

2023-06-13 13:10 UTC, nagyad commented on translations/oe_content-da.po
> +msgstr "jan."
But what if that is their way to make the abbreviation?

2023-06-13 15:23 UTC, 22Alexandra commented on translations/oe_content-da.po
> +msgstr "jan."
They use %B for the long month name and %b for short month name. Seems good now, thanks.

2023-06-13 15:24 UTC, 22Alexandra approved these changes

2023-06-26 14:36 UTC, sergepavle approved these changes

2023-06-29 16:30 UTC, merged