EWPP-3827: Re-roll entity_browser patch.
openeuropa/oe_content pull request #603
Opened 2023-12-12 09:41 UTC by nagyad

2023-12-12 16:00 UTC, 22Alexandra submitted a review, later dismissed

2023-12-12 16:10 UTC, 22Alexandra commented
We should update the info files within this PR too, otherwise we might forget.

2023-12-13 07:46 UTC, 22Alexandra approved these changes, later dismissed

2023-12-13 07:58 UTC, brummbar requested changes

2023-12-13 07:58 UTC, brummbar commented on phpunit.xml.dist
> +    <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["${selenium.browser}", {"browserName":"chrome","chromeOptions":{"w3c": false, "args":["--no-sandbox", "--start-maximized", "--disable-gpu", "--windo
Window size here should reflect the old one and be 1280x800.

2023-12-13 07:58 UTC, brummbar commented on phpunit.xml.dist
> +    <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["${selenium.browser}", {"browserName":"chrome","chromeOptions":{"w3c": false, "args":["--no-sandbox", "--start-maximized", "--disable-gpu", "--windo
We also need to bring these to behat.yml.dist .
I'm copying here the ones from joinup, update them based on the ones used above:
```
capabilities:
          browser: chrome
          nativeEvents: true
          marionette: true
          browserName: chrome
          version: '*'
          extra_capabilities:
            chromeOptions:
              w3c: false
              args:
                - '--no-sandbox'
                - '--start-maximized'
                - '--disable-gpu'
                - '--window-size=1600,1200'
                - '--disable-dev-shm-usage'
                - '--disable-setuid-sandbox'
                - '--disable-web-security'
                - '--DNS-prefetch-disable'
                - '--disable-translate'
                - '--ignore-certificate-errors'
                - '--test-type'
                - '--disable-extensions'
                - '--incognito'
                - '--disable-infobars'
                - '--allowed-ips=*'
                - '--whitelisted-ips=*

2023-12-13 07:58 UTC, brummbar commented on .drone.yml
> +    - { PHP_VERSION: 8.2, CORE_VERSION: 10.1, TYPE: phpunit }
we should add also 8.1 and 10.1. Before the matrix had only 3 entries as 10.x was not compatible with 8.0.

2023-12-13 12:14 UTC, brummbar approved these changes

2023-12-13 12:25 UTC, 22Alexandra approved these changes

2023-12-13 12:25 UTC, merged