EWPP-3855: Support D10.2 and drop D9.
openeuropa/oe_content pull request #609
Opened 2024-01-22 14:24 UTC by nagyad

2024-01-22 14:26 UTC, brummbar requested changes

2024-01-22 14:26 UTC, brummbar commented on .drone.yml
> +      # Change the patch for 10.2.x.
Let's do the opposite, add 10.2.x patch in composer.json and replace it for 10.1. We install by default on 10.2 from the composer.json of the component.

2024-01-24 13:56 UTC, drishu approved these changes, later dismissed

2024-01-29 16:16 UTC, miguelst commented
Hello, 

We need to upgrade urgently our website to Drupal 10, but the upgrade is blocked by this component as it does not support Drupal 10.2 version, and with previous version the upgrade also is blocked due other dependencies. 
Could you provide a estimation about when the component will support it?

Thanks,
Miguel

2024-02-05 16:30 UTC, brummbar requested changes

2024-02-05 16:30 UTC, brummbar commented on composer.json
> +                "https://www.drupal.org/project/drupal/issues/2230909": "https://www.drupal.org/files/issues/2023-12-21/2230909-309.patch"
We need to warn people that this patch is not working for Drupal 10.1.
```suggestion
                "Drupal 10.2.x only - see README.md for 10.1.x - https://www.drupal.org/project/drupal/issues/2230909": "https://www.drupal.org/files/issues/2023-12-21/2230909-309.patch"
```

2024-02-05 16:30 UTC, brummbar commented on README.md
> +composer config --merge --json "extra.patches.drupal/core" '{"https://www.drupal.org/project/drupal/issues/2230909": "https://www.drupal.org/files/issues/2022-07-26/2230909-269.patch"}'
This is ok for our drone, but users of this module need an additional command:
```
composer config --merge --json "extra.patches-ignore.openeuropa/oe_content" '{"drupal/core": {"Drupal 10.2.x only - see README.md for 10.1.x - https://www.drupal.org/project/drupal/issues/2230909": "https://www.drupal.org/files/issues/2023-12-21/2230909-309.patch"}}'
```
They need to ignore the patch provided by oe_content and add the other.

2024-02-05 16:31 UTC, brummbar requested changes

2024-02-05 16:31 UTC, brummbar commented on modules/oe_content_project/src/Drush/Commands/ProjectCommands.php
> +  #[CLI\Command(name: 'oe_content_project:copy-budget-field-values', aliases: [])]
We cannot change the name of the command.

2024-02-05 16:54 UTC, brummbar submitted a review, later dismissed

2024-02-06 09:30 UTC, brummbar approved these changes

2024-02-06 11:37 UTC, merged