EWPP-4011: Update Twitter label to X.
openeuropa/oe_content pull request #617
Opened 2024-04-08 06:35 UTC by 22Alexandra

2024-04-08 14:27 UTC, nagyad requested changes

2024-04-08 14:27 UTC, nagyad commented on modules/oe_content_entity/modules/oe_content_entity_contact/oe_content_entity_contact.post_update.php
> +  $field_storage->save();
We should do nothing if there is no twitter in the config, not even re-save.

2024-04-08 14:27 UTC, nagyad commented on modules/oe_content_social_media_links_field/oe_content_social_media_links_field.post_update.php
> +  $field_storage->save();
We should do nothing if there is no twitter in the config, not even re-save.

2024-04-09 10:32 UTC, nagyad approved these changes, later dismissed

2024-04-09 13:48 UTC, imanoleguskiza approved these changes

2024-04-09 13:48 UTC, imanoleguskiza commented on modules/oe_content_entity/modules/oe_content_entity_contact/oe_content_entity_contact.post_update.php
> +  if (!isset($settings['allowed_values']['twitter'])) {
In order to avoid potential changes from other sites (who knows), we should probably check that the value of the array is also "Twitter", so if they have already changed it (to X or somehting else) we do nothing.

2024-04-15 07:26 UTC, nagyad approved these changes

2024-04-15 07:28 UTC, imanoleguskiza approved these changes

2024-04-15 07:45 UTC, merged