EWPP-4288: Add check if organiser field exists.
openeuropa/oe_content pull request #622
Opened 2024-06-06 16:14 UTC by nagyad

2024-06-17 13:35 UTC, 22Alexandra requested changes
Is `AuthorSkosUpdater` still needed?

2024-06-17 13:35 UTC, 22Alexandra commented on modules/oe_content_project/README.md
> +As of 4.x the following float type fields had been removed:
So these fields were supposed to be removed in the next major considering the previous statement. Are we going to 4.x or is it ok to remove the fields in a minor version?

2024-06-17 13:46 UTC, nagyad commented on modules/oe_content_project/README.md
> +As of 4.x the following float type fields had been removed:
We will have to merge this into a new 4.x branch and we will go to a new major after this.

2024-06-17 13:49 UTC, nagyad commented
The `AuthorSkosUpdater` is needed because we made it as optional since we are not deleting or deprecating oe_author fields in this component, except EWPP where it is a project decision.

2024-06-24 09:56 UTC, sergepavle commented
Are we planning still to keep `PersonNodeUpdater` service?

2024-06-24 10:03 UTC, sergepavle commented on modules/oe_content_project/oe_content_project.post_update.php
> +      $field_storage->delete();
For safety better anyway to check if the field exists before trying to remove it.

2024-06-25 13:55 UTC, sergepavle submitted a review, later dismissed

2024-06-25 14:21 UTC, 22Alexandra submitted a review, later dismissed

2024-06-27 10:49 UTC, sergepavle approved these changes

2024-06-27 10:54 UTC, hernani approved these changes

2024-06-27 10:55 UTC, merged